from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('anime.html', views.anime),
    path('china_coffee.html', views.china_coffee),
    path('coffee.html', views.coffee),
    path('cosplay.html', views.cosplay),
    path('loging.html', views.loging),
    path('japanese_tea.html', views.japanese_tea),
    path('restaurant.html', views.restaurant),
    path('tea.html', views.tea),
    path('Americano.html', views.americano),
    path('Bicherin.html', views.bicherin),
    path('Breve.html', views.breve),
    path('Cappuccino.html', views.cappuccino),
    path('Con_panna.html', views.con_panna),
    path('Corretto.html', views.corretto),
    path('Doppio.html', views.doppio),
    path('Espresso.html', views.espresso),
    path('Flat_White.html', views.flat_white),
    path('Fredo.html', views.fredo),
    path('Glasse.html', views.glasse),
    path('Honey_Raf.html', views.honey_raf),
    path('Irish.html', views.irish),
    path('Latte.html', views.latte),
    path('Latte_Macchiato.html', views.latte_macchiato),
    path('Lungo.html', views.lungo),
    path('Macchiato.html', views.macchiato),
    path('Marochino.html', views.marochino),
    path('Mocha.html', views.mocha),
    path('Raf_coffee.html', views.raf_coffee),
    path('Ristretto.html', views.ristretto),
    path('Romano.html', views.romano),
    path('Triplo.html', views.triplo),
    path('Viennese_coffee.html', views.viennese_coffee),
]
